# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-15 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectconcept',
            name='census_category',
            field=models.CharField(blank=True, default='Population', max_length=128),
        ),
        migrations.AlterField(
            model_name='subjectconcept',
            name='source',
            field=models.CharField(blank=True, default='American Community Survey Subject Definitions', max_length=64),
        ),
    ]
