# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-20 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap', '0004_auto_20160302_1645'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='geography',
            unique_together=set([('geo_level', 'geo_code', 'year')]),
        ),
    ]
