# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-21 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap', '0005_unique-geo-add-year'),
    ]

    operations = [
        migrations.AddField(
            model_name='geography',
            name='version',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.RunSQL("""
        update wazimap_geography set version = year::text
        """),
        migrations.AlterUniqueTogether(
            name='geography',
            unique_together=set([('geo_level', 'geo_code', 'version')]),
        ),
        migrations.RemoveField(
            model_name='geography',
            name='year',
        ),
    ]
