# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-13 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap', '0009_data_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtable',
            name='denominator_key',
            field=models.CharField(blank=True, help_text=b'The key value of the rightmost field that should be used as the "total" column, instead of summing over the values for each row. This is necessary when the table doesn\'t describe a true partitioning of the dataset (ie. the row values sum to more than the total population).  This will be used as the total column once the id of the column has been calculated.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fieldtable',
            name='description',
            field=models.CharField(blank=True, help_text=b'Helpful description of this table (optional). Generated automatically for FieldTables if left blank.', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='fieldtable',
            name='has_total',
            field=models.BooleanField(default=True, help_text=b'Does it make sense to calculate a total column and express percentages for values in this table?'),
        ),
        migrations.AddField(
            model_name='fieldtable',
            name='value_type',
            field=models.CharField(choices=[(b'Integer', b'Integer'), (b'Float', b'Float')], default=b'Integer', max_length=20),
        ),
        migrations.AddField(
            model_name='simpletable',
            name='description',
            field=models.CharField(blank=True, help_text=b'Helpful description of this table (optional). Generated automatically for FieldTables if left blank.', max_length=1024, null=True),
        ),
    ]
