# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-06 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap', '0010_null-total-column'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='citation',
            field=models.TextField(blank=True, help_text=b'What the user should use when citing this data.', max_length=250, null=True),
        ),
    ]
