# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-12 07:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap', '0011_release_citation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtable',
            name='denominator_key',
            field=models.CharField(blank=True, help_text=b'The key value of the rightmost field that should be used as the "total" column, instead of summing over the values for each row. This is necessary when the table doesn\'t describe a true partitioning of the dataset (ie. the row values sum to more than the total population).  This will be used as the total column once the id of the column has been calculated.', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fieldtable',
            name='fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150, unique=True), help_text=b'Comma-separated ordered list of fields this table describes.', size=None),
        ),
        migrations.AlterField(
            model_name='release',
            name='citation',
            field=models.TextField(blank=True, help_text=b'What the user should use when citing this data.', null=True),
        ),
    ]
