# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-03 12:21
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import wazimap.models.data


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap', '0011_release_citation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text=b'Name for this table. No spaces.', max_length=1024, unique=True)),
                ('universe', models.CharField(help_text=b"Universe this table describes, such as 'Population', 'Households', or 'Youth aged 15-24'.", max_length=1024)),
                ('stat_type', models.CharField(choices=[(b'number', b'number'), (b'percentage', b'percentage')], default=b'number', max_length=10)),
                ('description', models.CharField(blank=True, help_text=b'Helpful description of this table (optional). Generated automatically for FieldTables if left blank.', max_length=1024, null=True)),
                ('fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, unique=True), help_text=b'Comma-separated ordered list of fields this table describes.', size=None)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wazimap.Dataset')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PointTableRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wazimap.PointTable')),
                ('db_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wazimap.DBTable')),
            ],
            bases=(models.Model, wazimap.models.data.BaseRelease),
        ),
        migrations.AlterField(
            model_name='release',
            name='citation',
            field=models.TextField(blank=True, help_text=b'What the user should use when citing this data.', null=True),
        ),
        migrations.AddField(
            model_name='pointtablerelease',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wazimap.Release'),
        ),
        migrations.AddField(
            model_name='pointtable',
            name='db_table_releases',
            field=models.ManyToManyField(through='wazimap.PointTableRelease', to='wazimap.DBTable'),
        ),
    ]
