# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-01-11 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap', '0011_release_citation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='citation',
            field=models.TextField(blank=True, help_text=b'What the user should use when citing this data.', null=True),
        ),
    ]
