# Generated by Django 2.2.6 on 2019-10-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap', '0013_port_to_python3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geography',
            name='geo_level',
            field=models.CharField(max_length=25),
        ),
    ]
